version: 1
frontend:
  phases:
    preBuild:
      commands:
        - echo "Installing dependencies"
        - yarn install
    build:
      commands:
        - echo "Building the static site"
        - yarn build
  artifacts:
    baseDirectory: build   # Output directory for React
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
