version: 1.0
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - npm run build --prod
  artifacts:
    baseDirectory: dist/meb-fe  # Replace with the correct app folder name
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
