version: 1
frontend:
  phases:
    preBuild:
      commands:
        - nvm install 18.19.1  # Install a compatible Node.js version
        - nvm use 18.19.1
        - yarn install
    build:
      commands:
        - yarn build --prod
  artifacts:
    baseDirectory: dist/meb-fe
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
