name: Publish Docker image

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
  # Step 5: Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "dist/meb-fe/browser/*"
          target: "/var/www/angular-app/"
          
  deploy:
    runs-on: self-hosted
    steps:
      - name: Restart NGINX
        run: sudo systemctl restart nginx
