
name: Publish Docker image

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: dangthanhdatuit/mep-fe

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  
  deploy:
    needs: push_to_registry
    runs-on: self-hosted
    steps:
      - name: Pull new Docker image
        run: sudo docker pull dangthanhdatuit/mep-fe:develop

      - name: Stop and remove existing container
        run: |
          if sudo docker ps -q --filter "name=mep-fe"; then
            sudo docker stop mep-fe && sudo docker rm mep-fe
          fi

      - name: Start new container
        run: sudo docker run -d --name mep-fe -p 4200:80 dangthanhdatuit/mep-fe:develop

      - name: Restart NGINX
        run: sudo systemctl restart nginx
