name: Publish Docker image

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install --legacy-peer-deps
      - run: npm run build --if-present
      - name: Clear contents of /var/www/html
        run: sudo rm -rf /var/www/html/*
      - name: Copy dist folder to /var/www/html
        run: sudo cp -r dist/meb-fe/browser* /var/www/html
      - name: Restart NGINX
        run: sudo systemctl restart nginx
